// <auto-generated />
using BlazorExplorer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorExplorer.Migrations
{
    [DbContext(typeof(BlazorExplorerContext))]
    [Migration("20210807161506_CreateDbTables")]
    partial class CreateDbTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorExplorer.Entities.Table01", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CampoTable01")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table01s");
                });

            modelBuilder.Entity("BlazorExplorer.Entities.Table02", b =>
                {
                    b.Property<int>("Table01Id")
                        .HasColumnType("int");

                    b.Property<string>("CampoTable02")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Table01Id");

                    b.ToTable("Table02s");
                });

            modelBuilder.Entity("BlazorExplorer.Entities.Table02", b =>
                {
                    b.HasOne("BlazorExplorer.Entities.Table01", null)
                        .WithOne("Table02")
                        .HasForeignKey("BlazorExplorer.Entities.Table02", "Table01Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorExplorer.Entities.Table01", b =>
                {
                    b.Navigation("Table02");
                });
#pragma warning restore 612, 618
        }
    }
}
